[package]
name = "wordfight"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", default-features = false }
bevy_anyhow_alert = "0.3"
bevy_replicon = "0.27"
serde = "1.0"
thiserror = "1.0"
