FROM rust:1.79

# name the cwd after our server app
WORKDIR /usr/src/server
COPY . .

EXPOSE 7636
EXPOSE 7637

RUN cargo install --path ./apps/server --profile release --locked

CMD ["wordfight-server"]
