[package]
name = "wordfight-server"
version = "0.1.0"
authors = ["Sean Sullivan <me@snen.dev>"]
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
wordfight = { path = "../../" }
server = { workspace = true }
bevy = { workspace = true }
