name: Deploy Webserver (Deno Deploy)
on:
  push:
    tags:
        - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number in the format `v1.2.3`'
        required: true
        type: string
env:
  SERVER_IP: ${{ vars.SERVER_IP }}
  SERVER_PORT: ${{ vars.SERVER_PORT }}
  SERVER_TOKENS_PORT: ${{ vars.SERVER_TOKENS_PORT }}

jobs:
  deploy:
    name: Deno Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install trunk
        run: "cargo install trunk"

      - name: Add wasm target
        run: "rustup target add wasm32-unknown-unknown"

      - name: Create asset directory
        run: "mkdir assets"

      - name: Build wasm
        run: "trunk build --release"
        env:
            SERVER_IP: $SERVER_IP
            SERVER_PORT: $SERVER_PORT
            SERVER_TOKENS_PORT: $SERVER_TOKENS_PORT

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "wordfight"
          entrypoint: "webserver.ts"
          root: ""
